sudo: required
services:
 - docker

before_install:
 - docker build -t neosystemcouk/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true neosystemcouk/react-test npm test