sudo: required
services:
  - docker

before_install:
   - docker build -t webcompclick/docker-react -f Dockerfile.dev .

   script:
    - docker run webcompclick/docker-react npm run test -- --coverage