sudo: required
services:
 - docker

before_install:
 - docker build -t webcompclick/react -f Dockerfile.dev .

script:
 - docker run -e CI=true webcompclick/react npm test
deploy:
 provider: elasrickbeanstalk
 region: "us-east-2"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-us-east-2-534849083337"
 bucket_patch: "docker-react"
 on:
  branch: master
access_key_id: "$AWS_ACCESS_KEY"
secret_Access_key:
  secure: "AWS_SECRET_KEY"